import datetime
from helperFunctions import *
from docplex.mp.model import Model
from docplex.util.environment import get_environment


# Set pyplot backend
plt.switch_backend('TkAgg')

# ---------------------------------------------------------------------------
# Initialize the problem data
# ---------------------------------------------------------------------------

# Date for energy price, load power and photovoltaic power data
loadDate = datetime.date(2017,3,1)

# Unit energy cost
unitCost = 550

# Typical load curve
typicalLoadCurve = [60,65,70,70,75,80,80,80,80,80,75,75,75,80,85,90,90,95,100,100,95,85,80,65]

# Loads supplied and consumed power data from csv file:
# loadPower: power consumed by the loads
# pvPower: power generated by the photovoltaic system
# averageNetLoadPower: average net load Power
# averageYearLoadPower: average year load power
loadPower = readExampleData("dem")
pvPower = readExampleData("PV")
# priceCreg = readExampleData("Cbolsa")
# loadPower, pvPower, averageNetLoadPower, averageYearLoadPower = readLoadPVData(loadDate,'59')

# Base case: System without battery storage or photovoltaic generation
priceFixed = [unitCost for i in range(24)]
priceCreg  = computeCregPrice(typicalLoadCurve, unitCost)
totalCostFixed = sum([priceFixed[t] * loadPower[t] for t in range(24)])
totalCostCreg  = sum([priceCreg[t] * loadPower[t] for t in range(24)])

# ---------------------------------------------------------------------------
# Build the model
# ---------------------------------------------------------------------------

def build_microgrid_model(mdl, Pl, Ppv, Cd, **kwargs):
    period = range(25)
    
    # Create parameters
    Es_nom = 20     # Nominal battery power
    eta_ch = 0.95   # Charge efficiency
    eta_dch = 0.95  # Discharge efficiency
    Pd_min = 0      # Minimum power supplied by the grid
    Pd_max = 50     # Maximum power supplied by the grid
    Pch_min = 0     # Minimum power charged to the batteries
    Pch_max = 20    # Maximum power charged to the batteries
    Pdch_min = 0    # Minimum power discharged from the batteries
    Pdch_max = 20   # Maximum power discharged from the batteries
    Es_mini = 0.2*Es_nom*5  # Minimum energy stored in the batteries
    Es_max = 0.8*Es_nom*5   # Maximum energy stored in the batteries

    # Create variables
    Pd   = mdl.continuous_var_list(period, lb=Pd_min,   ub = Pd_max,   name='Pd')
    Pch  = mdl.continuous_var_list(period, lb=Pch_min,  ub = Pch_max,  name='Pch')
    Pdch = mdl.continuous_var_list(period, lb=Pdch_min, ub = Pdch_max, name='Pdch')
    Es   = mdl.continuous_var_list(period, lb=Es_mini,  ub = Es_max,   name='Es')
    q    = mdl.binary_var_list(period, name="q")     # Binary variable that defines the state of the inverter (xbat=1: charging, xbat=0: discharging)

    # Create constraints
    mdl.add_constraints((Es[t] == Es[t-1] + eta_ch*Pch[t-1] - eta_dch*Pdch[t-1] for t in range(1,25)), names="C(1b)")
    mdl.add_constraints((Pd[t] == Pl[t] + Pch[t] - Pdch[t] - Ppv[t] for t in range(24)), names="C(1c)")
    mdl.add_constraint(Es[0] == Es[24], ctname="C(1d)")
    mdl.add_constraints((Pch[t] <= q[t]*Pch_max for t in range(24)), names="C(1f)")
    mdl.add_constraints((Pdch[t] <= (1-q[t])*Pdch_max for t in range(24)), names="C(1g)")
    mdl.add_constraints((Pd[t] <= Pl[t] for t in range(24)), names="C(1h)")

    # Objective function
    total_cost = mdl.sum(Cd[t] * Pd[t] for t in range(24))    
    mdl.minimize(total_cost)
    return mdl
# ---------------------------------------------------------------------------
# Solve the model and diplay the results
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    with Model(name="microgrid") as mdl:
        # Create the model
        mdl = build_microgrid_model(mdl, loadPower, pvPower, priceCreg)
        
        # Solve the model
        msoln = mdl.solve()
        
        # Extract the values of the decision variables
        Pd = [var.solution_value for var in mdl.find_matching_vars('Pd_')]
        Pch = [var.solution_value for var in mdl.find_matching_vars('Pch_')]
        Pdch = [var.solution_value for var in mdl.find_matching_vars('Pdch_')]
        Es = [var.solution_value for var in mdl.find_matching_vars('Es_')]
        q = [var.solution_value for var in mdl.find_matching_vars('q_')]

        # Calculate the total cost
        totalCost = mdl.objective_value
        status = mdl.solve_details.status
        
        # Display the results
        print(f"Solution status: {status}")
        print(f"Objective value: {totalCost}")
        
        # # Print the results
        print(f"Load Date: {loadDate}, Total Energy Cost = ${totalCost:.2f}")
    
        Cd = priceCreg
        Ppv = pvPower
        Pl = loadPower
        
        fig, axs = plt.subplots(3, 1, constrained_layout=True, figsize=(10,13))
        # figtitle = f"Load Date: {loadDate}, Total Energy Cost = ${totalCost:.2f}"
        figtitle = f"Sistema de Alamcenamiento sin DR, Costo total = ${totalCost:.2f}"

        fig.suptitle(figtitle)
        axs[0].step(range(25),Cd + [Cd[-1]], where='post')
        axs[0].legend(["Cd"],loc='upper left')
        axs[0].minorticks_on()
        # axs[0].grid(b=True, which='major', color='darkgray', linestyle='-')
        # axs[0].grid(b=True, which='minor', color='lightgray', linestyle='--')
        axs[0].set_ylabel('Costo [$]')
        axs[0].set_xlim([0,24])
        loadCurve = typicalLoadCurve + [typicalLoadCurve[-1]]
        axs0b = axs[0].twinx()
        axs0b.step(range(25), loadCurve, where='post', linestyle='--', color='tab:red')
        axs0b.tick_params(axis='y', labelcolor='tab:red')
        axs0b.legend(["Typical Load Curve"], loc='upper right')
        axs0b.set_ylabel('Potencia [%]', color='tab:red')
        axs0b.tick_params(axis='y', colors='tab:red')
        axs0b.set_xlim([0,24])
        axs[1].step(range(25),Pd, where='post', linestyle='-')
        axs[1].step(range(25),Ppv + [Ppv[-1]], where='post', linestyle='-')
        axs[1].step(range(25),Pl + [Pl[-1]], where='post', linestyle='--')
        axs[1].legend(["Pd", "Ppv", "Pl"], loc="upper left", ncol=3) 
        axs[1].minorticks_on()
        # axs[1].grid(b=True, which='major', color='darkgray', linestyle='-')
        # axs[1].grid(b=True, which='minor', color='lightgray', linestyle='--')
        axs[1].set_ylabel('Potencia [kW]')
        axs[1].set_xlim([0,24])
        axs[2].step(range(25),Pch, where='post', linestyle='-')
        axs[2].step(range(25),Pdch, where='post', linestyle='-')
        axs[2].legend(["Pch", "Pdch"], loc='upper left', ncol=2) 
        axs[2].minorticks_on()
        # axs[2].grid(b=True, which='major', color='darkgray', linestyle='-')
        # axs[2].grid(b=True, which='minor', color='lightgray', linestyle='--')
        axs[2].set_xlabel('Tiempo [h]')
        axs[2].set_ylabel('Potencia [kW]')
        axs[2].set_xlim([0,24])
        axs2b = axs[2].twinx()
        axs2b.plot(range(25),Es, linestyle='--', color='tab:red')
        axs2b.tick_params(axis='y', labelcolor='tab:red')
        axs2b.legend(["Es"], loc='upper right')
        axs2b.set_ylabel('Energía [kWh]', color='tab:red')
        axs2b.tick_params(axis='y', colors='tab:red')
        axs2b.set_xlim([0,24])
        plt.show()